---
title: "CV"
author: "Lukas"
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  word_document: default
  html_document:
    df_print: paged
geometry: margin=1in

jobtitle: Postdoctoral Research Fellow, London School of Economics and Political Science
address: "Centre Building, Houghton St, London WC2A 2AZ"
fontawesome: yes
email: f.torres-raposo@lse.ac.uk
phone: $+44 7463631521$
web: ftraposo.github.io/home/
github: ftraposo 
twitter: ftraposo
updated: yes
keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: black
urlcolor: blue
---

<!-- 
Space for notes to yourself that are not displayed in the PDF output
-->


# RESEARCH INTERESTS

- Political Economy 
- Experimental Methods



# Academic Positions

- **London School of Economics and Political Science**, my position \hfill $2023$ - present  \


# EDUCATION

- **University of Oxford**, DPhil in Politics \hfill $2019$ - present  \
Dissertation: Essays in Political Economy \
Supervisor: Prof. Raymond Duch 

- **Queen Mary University of London**, MSc in Economics \hfill $2018$  \

- **University of Oxford**, Master of Public Policy \hfill $2015$  \

# Affiliations

- **My University** \hfill $2023$ \
Supervisor: XX


# RESEARCH

## Working Papers

- "[Government Audits of Municipal Corruption and Belief Updating: Experimental from a Field Experiment.](https://raymondduch.com/files/government-audits-municipal-corruption-belief.pdf)", (joint with Raymond Duch)

- "[Choice Architecture for Messaging Corruption: Evidence from an Adaptive Experiment](https://www.socialscienceregistry.org/trials/7233)", (joint with my Raymodn Duch)

- "[Measuring Corruption using Bayesian Randomise Item Response Model](https://www.socialscienceregistry.org/trials/7233)", (joint with my Raymodn Duch)


## Work in Progress

- "[Deeds and Words: Linking Attitudes and Actions on Global Poverty and Developmen](my URL)", (joint with my co-authors)

- "[The Spillover Effects of Audits](my URL)", (joint with my co-authors)

## Journal Publications


- "[My title](my URL)", (joint with my co-authors), in the journal, published year.


# AWARDS AND GRANTS 

## Awards

- My second award (£ $00,000$) \hfill $2023$ 
- My first award (€ $0,000$) \hfill $2023$

## Scholarships
- My second scholarship (£ $00,000$) \hfill $2019$ - $2023$ 
- My first scholarship (£ $00,000$) \hfill $2019$ - $2023$


## Grants

- My second grant (£ $000,000$) \hfill $2019$ - $2023$ 
- My first grant (£ $00,000$) \hfill $2019$ - $2023$
 

# PRESENTATIONS

## Invited Talks
<!--  -->

**$2024$ (scheduled):** 

**$2023$:** 

**$2022$:** 

**$2021$ and prior:** 

## Conferences and Workshops

**$2023$:** 

**$2022$:** 

**$2021$ and prior:** 

# ENGAGEMENT

## Reports and Book Chapters

- "[My title](my URL)", (joint with my co-authors), in the book, published year.


## Selected Interviews and Media Quotes

- "[Title](URL)", Outlet, $12/2022$.


# TEACHING

## **My second university**

- GV481 Quantitative Analysis for Political Science, (postgraduate level) \hfill $2023$ \
*Postdoctoral Fellow*

- Introduction to Quantitative Research Methods (postgraduate level) \hfill $2021$ \
*Teaching Fellow*

- Causal Inference (postgraduate level) \hfill $2021$ \
*Teaching Assistant*

- Advanced topics of Development Economics (undergraduate level) \hfill $2021$ \
*Teaching Assistant*

- Quantitative Methods (undergraduate level) \hfill $2021$ \
*Teaching Assistant*

## **My first university**

- My course (postgraduate level) \hfill $2021$ \
*My position*

- My course (postgraduate level) \hfill $2020$ \
*My position*


# SERVICE
- **Reviewer**: 
- **Organizer**: 

# PROFESSIONAL RESEARCH EXPERIENCE

-	**My Employer**, *My position* \hfill $2020$ - $2022$  


# SKILLS AND LANGUAGES 

- *Data Analysis:* R
- *Software*: \LaTeX, HTML, Git, Markdown, Quarto
-	*Languages:* English (fluent), Spanish (native), Italian (intermediate)

